### 服务器配置
server:
  port: 8002

# 项目相关配置
easyadmin:
  # 名称
  name: EasyAdmin
  #作者
  author: SingleZhang
  #email
  email: 405780096@qq.com
  #blog
  blog: https://www.jianshu.com/u/c72c64b977eb
  # 版本
  version: 1.0.1
  # 版权年份
  copyrightYear: 2020
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置E:/easyadmin/upload，Linux配置 /home/easyadmin/upload）
  profile: E:/easyadmin/upload
  baseUrl: http://f.easyadmin.com
  # 获取ip地址开关
  addressEnabled: true


# Spring配置
spring:
  mvc:
    favicon.enabled: false
  # 模板引擎
  thymeleaf:
    prefix: classpath:/templates
    suffix: .html
    mode: HTML
    encoding: utf-8
    servlet.content-type: text/html
    # 禁用缓存
    cache: false
  #jackson对响应回去的日期参数进行格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    active: druid
  # redis 配置
  redis:
    # 地址
    host: localhost
    # 端口，默认为6379
    port: 6379
    # 密码
    password:
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
  devtools:
    restart:
      # 热部署开关
      enabled: true


# MyBatis
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.zhxin
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis-config.xml

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

#阿里云OSS
aliyun-oss:
  endPoint: oss-cn-shanghai.aliyuncs.com
  keyId:    LTAI9OO50bp6a6xd
  keySecret: r2SzShgEUu7bmvZD1PpH8mNBitHCPT
  bucketName: ylkadmin
  filDir: easyadmin

#token
token:
  header: Authorization
  expire: 60
  jwtSecret: abcdefg+(Single)+higklmn+(Zhang)+opqrstuvwxyz